name: zine-maker-ipfs
region: nyc
functions:
  - name: functions
    github:
      repo: virgilvox/zine-maker
      branch: feature/ipfs-share
      deploy_on_push: true
    source_dir: do-functions
    routes:
      - path: /api/
    envs:
      - key: IPFS_DROPLET_HOST
        scope: RUN_TIME
      - key: IPFS_DROPLET_ADMIN_PASS
        scope: RUN_TIME
        type: SECRET
      - key: IPFS_DROPLET_ADMIN_USER
        scope: RUN_TIME
      - key: IPFS_MFS_MANIFEST_PATH
        scope: RUN_TIME
      - key: IPFS_IPNS_KEY
        scope: RUN_TIME
      - key: IPFS_API_SECRET
        scope: RUN_TIME
        type: SECRET

static_sites:
  - name: web
    github:
      repo: virgilvox/zine-maker
      branch: feature/ipfs-share
      deploy_on_push: true
    source_dir: .
    build_command: npm ci && npm run build
    output_dir: dist
    routes:
      - path: /

