name: zine-maker-ipfs
region: nyc
functions:
  - name: functions
    github:
      repo: virgilvox/zine-maker
      branch: feature/ipfs-share
      deploy_on_push: true
    source_dir: do-functions
    routes:
      - path: /api/
    envs: []

static_sites:
  - name: web
    github:
      repo: virgilvox/zine-maker
      branch: feature/ipfs-share
      deploy_on_push: true
    source_dir: .
    build_command: npm ci && npm run build
    output_dir: dist
    routes:
      - path: /

