environment:
  PINATA_JWT: "${PINATA_JWT}"
  PINATA_API_KEY: "${PINATA_API_KEY}"
  PINATA_API_SECRET: "${PINATA_API_SECRET}"
  PINATA_GATEWAY_BASE: "${PINATA_GATEWAY_BASE}"
  REGISTRY_CID: "${REGISTRY_CID}"

packages:
  - name: zine
    environment:
      PINATA_JWT: "${PINATA_JWT}"
      PINATA_API_KEY: "${PINATA_API_KEY}"
      PINATA_API_SECRET: "${PINATA_API_SECRET}"
      PINATA_GATEWAY_BASE: "${PINATA_GATEWAY_BASE}"
      REGISTRY_CID: "${REGISTRY_CID}"
    actions:
      - name: publish
        runtime: 'nodejs:default'
        web: true
      - name: registry
        runtime: 'nodejs:default'
        web: true
      - name: envcheck
        runtime: 'nodejs:default'
        web: true

