environment:
  PINATA_JWT: "${PINATA_JWT}"
  PINATA_API_KEY: "${PINATA_API_KEY}"
  PINATA_API_SECRET: "${PINATA_API_SECRET}"
  PINATA_GATEWAY_BASE: "${PINATA_GATEWAY_BASE}"
  REGISTRY_CID: "${REGISTRY_CID}"
  REGISTRY_NAME: "${REGISTRY_NAME}"
  IPFS_DROPLET_HOST: "${IPFS_DROPLET_HOST}"
  IPFS_DROPLET_ADMIN_USER: "${IPFS_DROPLET_ADMIN_USER}"
  IPFS_DROPLET_ADMIN_PASS: "${IPFS_DROPLET_ADMIN_PASS}"
  IPFS_MFS_MANIFEST_PATH: "${IPFS_MFS_MANIFEST_PATH}"
  IPFS_IPNS_KEY: "${IPFS_IPNS_KEY}"

packages:
  - name: zine
    actions:
      - name: publish
        runtime: 'nodejs:18'
        web: true
      - name: registry
        runtime: 'nodejs:18'
        web: true
      - name: envcheck
        runtime: 'nodejs:18'
        web: true

